// Script to add QLD projects via API endpoint
const projects = [
  // Original 3 projects
  {
    suburb: "SLACKS CREEK",
    street: "5 GEEBA ST",
    specs: "SUPERIOR",
    project_cost: "$193,240",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "BROWNS PLAINS",
    street: "55 YANCY ST",
    specs: "SUPERIOR",
    project_cost: "$189,730",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "SAMFORD VALLEY",
    street: "50 GREGGS RD",
    specs: "SUPERIOR",
    project_cost: "$233,880",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  // New batch 1
  {
    suburb: "KARALEE",
    street: "9–11 Melbourne Street",
    specs: "AFFORDABLE",
    project_cost: "$210,850",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "CRESTMEAD",
    street: "44 Royena",
    specs: "SUPERIOR",
    project_cost: "$193,000",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "ROCHEDALE",
    street: "8 Tarcoola Street",
    specs: "AFFORDABLE",
    project_cost: "$200,600",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "MUNDOOLUN",
    street: "61–65 Bredalbane Street",
    specs: "SUPERIOR",
    project_cost: "$236,160",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "SALISBURY",
    street: "416 Orange Grove Road",
    specs: "SUPERIOR",
    project_cost: "$243,300",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "MILES",
    street: "16 Acacia Drive",
    specs: "AFFORDABLE",
    project_cost: "$266,320",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "NEW BEITH",
    street: "12–18 Horseshoe",
    specs: "SUPERIOR",
    project_cost: "$269,360",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "MOUNT WARREN PARK",
    street: "7 Lane Court",
    specs: "AFFORDABLE",
    project_cost: "$199,380",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "DELANEYS CREEK",
    street: "26 Attunga Court",
    specs: "AFFORDABLE",
    project_cost: "$205,600",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "NEW BEITH",
    street: "7–11 Bidyan Boulevard",
    specs: "SUPERIOR",
    project_cost: "$262,031",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "CALAMVALE",
    street: "12 Begonia Place",
    specs: "SUPERIOR",
    project_cost: "$251,370",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "EAGLEBY",
    street: "6 Melwood Street",
    specs: "AFFORDABLE",
    project_cost: "$226,790",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "NINGI",
    street: "2–6 Triton",
    specs: "AFFORDABLE",
    project_cost: "$269,810",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "SUNNYBANK",
    street: "2–6 Triton",
    specs: "AFFORDABLE",
    project_cost: "$178,800",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "WEST END",
    street: "9 Forbes Street",
    specs: "SUPERIOR",
    project_cost: "$254,100",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "BELLBIRD PARK",
    street: "30 Sherwood Crescent",
    specs: "AFFORDABLE",
    project_cost: "$226,980",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "SUNNYBANK HILLS",
    street: "587 Compton",
    specs: "SUPERIOR",
    project_cost: "$242,460",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "TINGALPA",
    street: "13 Cox Close",
    specs: "AFFORDABLE",
    project_cost: "$214,600",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "WAVELL HEIGHTS",
    street: "23 Newman Road",
    specs: "AFFORDABLE",
    project_cost: "$227,000",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "ELI WATERS",
    street: "10 Kestrel Court",
    specs: "SUPERIOR",
    project_cost: "$238,800",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "EDENS LANDING",
    street: "42 Avonmore Street",
    specs: "AFFORDABLE",
    project_cost: "$185,000",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "REDCLIFFE",
    street: "9 Highland Street",
    specs: "SUPERIOR",
    project_cost: "$192,340",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "LABRADOR",
    street: "52 Whiting Street",
    specs: "SUPERIOR",
    project_cost: "$209,300",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "REDBANK PLAINS",
    street: "51 Blaxland Crescent",
    specs: "SUPERIOR",
    project_cost: "$245,630",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "KALLANGUR",
    street: "8 Glenmore Street",
    specs: "AFFORDABLE",
    project_cost: "$223,825",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "BIRKDALE",
    street: "18–20 Creswick Place",
    specs: "SUPERIOR",
    project_cost: "$215,770",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "BEERBURRUM",
    street: "85 Murphys Road",
    specs: "AFFORDABLE",
    project_cost: "$315,880",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "LOGAN CENTRAL",
    street: "7 Yugumbri Crescent",
    specs: "SUPERIOR",
    project_cost: "$308,940",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  // Newly added
  {
    suburb: "BURNSIDE",
    street: "21 Tramline Rise",
    specs: "AFFORDABLE",
    project_cost: "$229,948",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "NOOSAVILLE",
    street: "1 Juron Street",
    specs: "AFFORDABLE",
    project_cost: "$227,300",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "MOUNT GRAVATT EAST",
    street: "81 Nightingale Street",
    specs: "AFFORDABLE",
    project_cost: "$196,940",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "PETRIE",
    street: "59 Rue Montaigne",
    specs: "SUPERIOR",
    project_cost: "$256,300",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "IPSWICH",
    street: "38 Warwick Road",
    specs: "AFFORDABLE",
    project_cost: "$194,200",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "BEENLEIGH",
    street: "45 Pheasant Avenue",
    specs: "SUPERIOR",
    project_cost: "$257,000",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "NERANG",
    street: "3 Kew",
    specs: "SUPERIOR",
    project_cost: "$260,550",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "CLIFTON",
    street: "75 Gillam Street",
    specs: "SUPERIOR",
    project_cost: "$307,560",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "MOUNT GRAVATT EAST",
    street: "89 Broadwater Road",
    specs: "SUPERIOR",
    project_cost: "$239,310",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "REGENTS PARK",
    street: "30 Charolton Place",
    specs: "AFFORDABLE",
    project_cost: "$187,080",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "BONOGIN",
    street: "6 Glenmore Drive",
    specs: "SUPERIOR",
    project_cost: "$234,410",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "LUTWYCHE",
    street: "2 Wellington Street",
    specs: "AFFORDABLE",
    project_cost: "$212,800",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "ROCHEDALE STH",
    street: "31 Tolverne",
    specs: "AFFORDABLE",
    project_cost: "$217,000",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "JIMBOOMBA",
    street: "57–67 Markwell",
    specs: "SUPERIOR",
    project_cost: "$255,290",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  // Next batch
  {
    suburb: "RUNCORN",
    street: "38 Ervatamia Street",
    specs: "SUPERIOR",
    project_cost: "$193,200",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "WOOLLOONGABBA",
    street: "49 Peterson Street",
    specs: "AFFORDABLE",
    project_cost: "$236,450",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "FLINDERS VIEW",
    street: "47 Edwards Street",
    specs: "AFFORDABLE",
    project_cost: "$202,750",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "KIPPA-RING",
    street: "18 Dorothy Street",
    specs: "SUPERIOR",
    project_cost: "$212,815",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "EAGLEBY",
    street: "14 Palmer Street",
    specs: "AFFORDABLE",
    project_cost: "$198,565",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "WOODRIDGE",
    street: "45 Orchid Street",
    specs: "AFFORDABLE",
    project_cost: "$231,030",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "INALA",
    street: "4 Aldebaran Street",
    specs: "SUPERIOR",
    project_cost: "$218,930",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "CHERMSIDE",
    street: "57 Meemar Street",
    specs: "SUPERIOR",
    project_cost: "$196,800",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "GRACEVILLE",
    street: "36 Park Road",
    specs: "AFFORDABLE",
    project_cost: "$232,100",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "GUMDALE",
    street: "235 Stanbrough",
    specs: "SUPERIOR",
    project_cost: "$296,156",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "GREENBANK",
    street: "29–33 Birdsville",
    specs: "SUPERIOR",
    project_cost: "$294,520",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "EVERTON PARK",
    street: "8 Everton Terrace",
    specs: "SUPERIOR",
    project_cost: "$268,540",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "UNDERWOOD",
    street: "34 Concourse",
    specs: "SUPERIOR",
    project_cost: "$278,000",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "LOGAN",
    street: "49 Cherry Street",
    specs: "SUPERIOR",
    project_cost: "$228,040",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "MITCHELTON",
    street: "190 Blackwood Street",
    specs: "AFFORDABLE",
    project_cost: "$215,700",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "INALA",
    street: "96 Biota Street",
    specs: "SUPERIOR",
    project_cost: "$226,260",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "VERNON",
    street: "8 Galatea Street",
    specs: "SUPERIOR",
    project_cost: "$211,800",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "REGENTS PARK",
    street: "21 Greenvale Court",
    specs: "AFFORDABLE",
    project_cost: "$186,420",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "GLENVIEW",
    street: "5 Whipbird",
    specs: "SUPERIOR",
    project_cost: "$320,340",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "KENMORE",
    street: "77 Sunset Road",
    specs: "AFFORDABLE",
    project_cost: "$212,330",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "KEPERRA",
    street: "17 Marble Street",
    specs: "AFFORDABLE",
    project_cost: "$218,620",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "BROWNS PLAINS",
    street: "8 Furzer Street",
    specs: "SUPERIOR",
    project_cost: "$242,462",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "DURRAK",
    street: "39 Randwick",
    specs: "AFFORDABLE",
    project_cost: "$217,250",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "BARRELLEN POINT",
    street: "1–5 Mitchel",
    specs: "SUPERIOR",
    project_cost: "$254,180",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "SALISBURY",
    street: "39 Salford Street",
    specs: "SUPERIOR",
    project_cost: "$246,860",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "SANDGATE",
    street: "25 Perkins Street",
    specs: "SUPERIOR",
    project_cost: "$231,060",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "TAMBORINE",
    street: "63–65 Martin Place",
    specs: "SUPERIOR",
    project_cost: "$226,240",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "UNDERWOOD",
    street: "9 Diana Street",
    specs: "AFFORDABLE",
    project_cost: "$172,170",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "NORTH BOOVAL",
    street: "6 Beth Street",
    specs: "SUPERIOR",
    project_cost: "$227,070",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "THORNLANDS",
    street: "6 Ransom Court",
    specs: "AFFORDABLE",
    project_cost: "$209,000",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "REDCLIFF",
    street: "9 Longland Street",
    specs: "SUPERIOR",
    project_cost: "$267,600",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "BOONDALL",
    street: "161 Lyndhurst",
    specs: "SUPERIOR",
    project_cost: "$207,460",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "PARKINSON",
    street: "8 Yengo Street",
    specs: "AFFORDABLE",
    project_cost: "$172,700",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "HARRISTON",
    street: "29 Merritt Street",
    specs: "SUPERIOR",
    project_cost: "$292,630",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "REDCLIFFE",
    street: "33 Hibiscus Avenue",
    specs: "AFFORDABLE",
    project_cost: "$181,700",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "STRAHPINE",
    street: "117 Peter Street",
    specs: "AFFORDABLE",
    project_cost: "$200,000",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "SHAILER PARK",
    street: "35 Moogara",
    specs: "SUPERIOR",
    project_cost: "$274,225",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "CALLAMVALE",
    street: "72 Sunflower Crescent",
    specs: "SUPERIOR",
    project_cost: "$225,555",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "KALLANGUR",
    street: "36 Leslie Street",
    specs: "AFFORDABLE",
    project_cost: "$213,670",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "WONGLEPOND",
    street: "81–95 Spponbill Road",
    specs: "SUPERIOR",
    project_cost: "$278,751",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "URANGAN",
    street: "106 Elizabeth Street",
    specs: "AFFORDABLE",
    project_cost: "$237,540",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "ELIMBAH",
    street: "9–11 Greentree Road",
    specs: "SUPERIOR",
    project_cost: "$259,260",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "EIGHT MILE PLAINS",
    street: "9 Byzance Close",
    specs: "SUPERIOR",
    project_cost: "$263,000",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "JINDALEE",
    street: "8 Moolingal Street",
    specs: "SUPERIOR",
    project_cost: "$270,430",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "REGENTS PARK",
    street: "8 Lantana Court",
    specs: "AFFORDABLE",
    project_cost: "$229,780",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "NORTH MACLEAN",
    street: "216–226 Teviot Road",
    specs: "SUPERIOR",
    project_cost: "$300,000",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "MUNDOOLUN",
    street: "42–44 Portsmounth Court",
    specs: "SUPERIOR",
    project_cost: "$260,940",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "CLONTARF",
    street: "7 Waterton Street",
    specs: "SUPERIOR",
    project_cost: "$222,850",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "REDBANK PLAINS",
    street: "12 Yarrow Court",
    specs: "AFFORDABLE",
    project_cost: "$216,630",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "INALA",
    street: "30 Krestel Street",
    specs: "SUPERIOR",
    project_cost: "$291,410",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "WOODRIDGE",
    street: "13 Phillip Street",
    specs: "SUPERIOR",
    project_cost: "$219,100",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  // Next batch
  {
    suburb: "WOODRIDGE",
    street: "30 Bruce Road",
    specs: "AFFORDABLE",
    project_cost: "$212,000",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "CLONTARF",
    street: "3 Conley Street",
    specs: "SUPERIOR",
    project_cost: "$217,535",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "GREENSLOPES",
    street: "30–32 Hunter Street",
    specs: "SUPERIOR",
    project_cost: "$283,690",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "RIVERHILLS",
    street: "20 Zambesi Street",
    specs: "SUPERIOR",
    project_cost: "$243,930",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "EAGLEBY",
    street: "28 Tario Street",
    specs: "SUPERIOR",
    project_cost: "$240,210",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "MERINGANDAN WEST",
    street: "4 Corella Street",
    specs: "SUPERIOR",
    project_cost: "$292,511",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "FORESTDALE",
    street: "13–17 Sheriff Street",
    specs: "SUPERIOR",
    project_cost: "$392,590",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "SUNNYBANK HILLS",
    street: "23 Kelceda Street",
    specs: "SUPERIOR",
    project_cost: "$249,900",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "LOGANLEA",
    street: "10 Edward Street",
    specs: "SUPERIOR",
    project_cost: "$220,500",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "REDCLIFFE",
    street: "9 Longland Street",
    specs: "SUPERIOR",
    project_cost: "$220,000",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "SALISBURY",
    street: "380 Orange Grove Road",
    specs: "SUPERIOR",
    project_cost: "$305,930",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "SILKSTONE",
    street: "5 Louise Court",
    specs: "SUPERIOR",
    project_cost: "$252,210",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "DECEPTION BAY",
    street: "3 St Lucia Street",
    specs: "SUPERIOR",
    project_cost: "$220,146",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "BUDERIM",
    street: "1 Geehi Court",
    specs: "AFFORDABLE",
    project_cost: "$235,450",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "CALOUNDRA",
    street: "8 Suller Street",
    specs: "AFFORDABLE",
    project_cost: "$208,650",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "STRATHPINE",
    street: "28 Bateman Street",
    specs: "AFFORDABLE",
    project_cost: "$252,515",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "WISHART",
    street: "23 Sovereign Close",
    specs: "SUPERIOR",
    project_cost: "$285,000",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "GREENBANK",
    street: "245–249 Ison Road",
    specs: "SUPERIOR",
    project_cost: "$281,350",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "CABOOLTURE",
    street: "220 King Street",
    specs: "AFFORDABLE",
    project_cost: "$224,340",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "SUNNYBANK",
    street: "5 Lavinia Street",
    specs: "AFFORDABLE",
    project_cost: "$242,650",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "LOGAN LEA",
    street: "10 Edward Street",
    specs: "SUPERIOR",
    project_cost: "$220,500",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "DECEPTION BAY",
    street: "25 Kate Avenue",
    specs: "AFFORDABLE",
    project_cost: "$210,180",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "CABOOLTURE",
    street: "7 Linwood Court",
    specs: "AFFORDABLE",
    project_cost: "$195,000",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "CRESTMEAD",
    street: "15 Pinehead Street",
    specs: "AFFORDABLE",
    project_cost: "$234,905",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "NINGI",
    street: "6 Grice Crescent",
    specs: "AFFORDABLE",
    project_cost: "$239,060",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "VICTORIA POINT",
    street: "47 Fir Street",
    specs: "SUPERIOR",
    project_cost: "$293,580",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "MARGATE",
    street: "11 Dover Road",
    specs: "SUPERIOR",
    project_cost: "$292,000",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "KOORALBYN",
    street: "30–40 Yulgibar Close",
    specs: "AFFORDABLE",
    project_cost: "$276,400",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "BIRKDALE",
    street: "14 Thomas Street",
    specs: "SUPERIOR",
    project_cost: "$298,530",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "BETHANIA",
    street: "6 Zircon Court",
    specs: "AFFORDABLE",
    project_cost: "$232,160",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "EAGLEBY",
    street: "3 Bedford",
    specs: "SUPERIOR",
    project_cost: "$237,510",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "NEW BEITH",
    street: "67–71 Melrose Place",
    specs: "SUPERIOR",
    project_cost: "$325,000",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "NERANG",
    street: "21 Spring Street",
    specs: "SUPERIOR",
    project_cost: "$354,040",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "CRESTMEAD",
    street: "7 Wisdom Way",
    specs: "AFFORDABLE",
    project_cost: "$229,350",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "MOOROOKA",
    street: "11 Fegen Drive",
    specs: "AFFORDABLE",
    project_cost: "$305,265",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "KALLANGUR",
    street: "8 Beattie Street",
    specs: "AFFORDABLE",
    project_cost: "$210,000",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "MIDDLE PARK",
    street: "7 Meadow",
    specs: "SUPERIOR",
    project_cost: "$255,000",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "LOGAN CENTRAL",
    street: "13 Moore Street",
    specs: "SUPERIOR",
    project_cost: "$290,000",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "BEAUDESERT",
    street: "8 Cedar Drive",
    specs: "SUPERIOR",
    project_cost: "$203,930",
    year: "2025",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  // New batch - 2026 projects
  {
    suburb: "STRATHPINE",
    street: "59 Samsonvale",
    specs: "SUPERIOR",
    project_cost: "$203,600",
    year: "2026",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "SUNNYBANK",
    street: "25 Agnes St",
    specs: "SUPERIOR",
    project_cost: "$228,100",
    year: "2026",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "TINGALPA",
    street: "25 Cashel St",
    specs: "SUPERIOR",
    project_cost: "$209,270",
    year: "2026",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "WOODHILL",
    street: "92-102 Monroe Drive",
    specs: "SUPERIOR",
    project_cost: "$241,350",
    year: "2026",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "MARSDEN",
    street: "95 Second Av",
    specs: "SUPERIOR",
    project_cost: "$203,500",
    year: "2026",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "SEVEN HILLS",
    street: "125 D'arcy Rd",
    specs: "SUPERIOR",
    project_cost: "$294,171",
    year: "2026",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "LOGAN CENTRAL",
    street: "4 Waitara St",
    specs: "SUPERIOR",
    project_cost: "$203,930",
    year: "2026",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  // New batch - February 2026 projects
  {
    suburb: "SEVEN HILLS",
    street: "125 D'arcy Rd",
    specs: "SUPERIOR",
    project_cost: "$294,171",
    year: "2026-02-01",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "LOGAN CENTRAL",
    street: "4 Waitara St",
    specs: "SUPERIOR",
    project_cost: "$203,930",
    year: "2026-02-01",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "JIMBOOMBA",
    street: "25-33 Alluring Ct",
    specs: "SUPERIOR",
    project_cost: "$351,730",
    year: "2026-02-01",
    state: "QLD",
    stream: "SGF - QLD",
    status: "Design Phase",
  },
  {
    suburb: "OXLEY",
    street: "1137 Oxley Rd",
    specs: "SUPERIOR",
    project_cost: "$331,675",
    year: "2026-02-01",
    state: "QLD",
    stream: "ATA",
    status: "Design Phase",
  },
  {
    suburb: "EAGLEBY",
    street: "33 Rinto",
    specs: "SUPERIOR",
    project_cost: "$248,280",
    year: "2026-02-01",
    state: "QLD",
    stream: "ATA",
    status: "Design Phase",
  },
  {
    suburb: "ROCKLEA",
    street: "45 Marshall Road",
    specs: "SUPERIOR",
    project_cost: "$272,600",
    year: "2026-01-01",
    state: "QLD",
    stream: "ATA",
    status: "Design Phase",
  },
];

async function addProjects() {
  try {
    console.log("Adding projects via API...");
    
    // Try different ports/URLs
    const urls = [
      "http://localhost:3001/api/projects/bulk",
      "http://192.168.0.222:3001/api/projects/bulk",
      "http://127.0.0.1:3001/api/projects/bulk",
    ];
    
    let response;
    let lastError;
    
    for (const url of urls) {
      try {
        console.log(`Trying ${url}...`);
        response = await fetch(url, {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify({ projects }),
        });
        
        if (response && (response.ok || response.status !== 0)) {
          break; // Success or got a response
        }
      } catch (e) {
        lastError = e;
        continue;
      }
    }
    
    if (!response) {
      throw new Error(`Could not connect to server. Tried: ${urls.join(", ")}`);
    }

    if (!response.ok) {
      const errorData = await response.json().catch(() => ({ error: response.statusText }));
      throw new Error(errorData.error || `HTTP ${response.status}`);
    }

    const result = await response.json();
    
    console.log("\n=== Summary ===");
    console.log(`Projects added: ${result.added}`);
    console.log(`Projects skipped: ${result.skipped}`);
    console.log(`Total processed: ${result.total}`);
    
    if (result.results) {
      console.log("\nDetails:");
      result.results.forEach((r, i) => {
        if (r.added) {
          console.log(`✓ Added: ${r.name} (ID: ${r.id})`);
        } else if (r.skipped) {
          console.log(`✗ Skipped: ${r.message}`);
        } else if (r.error) {
          console.log(`✗ Error: ${r.error}`);
        }
      });
    }
    
    console.log("\n✓ Project addition completed successfully!");
    process.exit(0);
  } catch (error) {
    console.error("\n✗ Project addition failed:", error.message);
    if (error.message.includes("ECONNREFUSED") || error.message.includes("fetch")) {
      console.error("Make sure the backend server is running on http://localhost:3001");
    }
    process.exit(1);
  }
}

// Check if fetch is available (Node.js 18+)
if (typeof fetch === 'undefined') {
  console.error("This script requires Node.js 18+ or you need to install node-fetch");
  process.exit(1);
}

addProjects();
