/** Core UI + sidebar menu colours. VIC Blue Light → menu blue; QLD Red Light → menu red; stream colours → menu green and banners. */

export const UI_THEME_COLOR_KEYS = [
  { key: "pageBackground", label: "Page" },
  { key: "pageText", label: "Text - Light" },
  { key: "textPrimary", label: "Text - Dark" },
  { key: "panelBackground", label: "Panel" },
  { key: "cardBackground", label: "Card" },
  { key: "inputBackground", label: "Input" },
  { key: "border", label: "Border" },
  { key: "outline", label: "Outline" },
  { key: "buttonPrimary", label: "Button" },
  { key: "menuPurple", label: "Menu Purple" },
  { key: "menuPurpleLight", label: "Menu Purple - Light" },
  { key: "vicBlue", label: "VIC Blue" },
  { key: "vicBlueLight", label: "VIC Blue - Light" },
  { key: "qldRed", label: "QLD Red" },
  { key: "qldRedLight", label: "QLD Red - Light" },
  { key: "streamGreen", label: "Stream Green" },
  { key: "streamGreenLight", label: "Stream Green - Light" },
  { key: "indicatorOrangeDark", label: "Indicator Orange - Dark" },
  { key: "indicatorOrangeLight", label: "Indicator Orange - Light" },
  { key: "projectCardBackground", label: "Project folder" },
];

export const UI_THEMES = {
  classic: {
    id: "classic",
    name: "Classic",
    description: "The original SGF look.",
    colors: {
      pageBackground: "#42464d",
      pageText: "#ffffff",
      textPrimary: "#323233",
      panelBackground: "#a1a1a3",
      cardBackground: "#ffffff",
      textMuted: "rgba(50, 50, 51, 0.6)",
      textSecondary: "#404049",
      inputBackground: "#f0f0f0",
      border: "#e0e0e0",
      buttonPrimary: "#323233",
      menuPurple: "#73658d",
      menuPurpleLight: "#B19CD9",
      outline: "#000000",
      projectCardBackground: "#323233",
      vicBlue: "#4D93D9",
      vicBlueLight: "#A6C9EC",
      qldRed: "#D54358",
      qldRedLight: "#F79198",
      streamGreen: "#92D050",
      streamGreenLight: "#CEEAB0",
      indicatorOrangeDark: "#a65800",
      indicatorOrangeLight: "#ff8800",
    },
  },
  dark: {
    id: "dark",
    name: "Dark",
    description: "Dark backgrounds with light text.",
    colors: {
      pageBackground: "#000000",
      pageText: "#f0f0f2",
      textPrimary: "#f0f0f2",
      panelBackground: "#1a1e28",
      cardBackground: "#353940",
      textMuted: "rgba(240, 240, 242, 0.65)",
      textSecondary: "#a1a1a3",
      inputBackground: "#1a1e28",
      border: "#4a4f58",
      buttonPrimary: "#e8e8ea",
      menuPurple: "#2c2339",
      menuPurpleLight: "#443658",
      outline: "#8a919c",
      projectCardBackground: "#353940",
      vicBlue: "#5a9fd4",
      vicBlueLight: "#3a6a8a",
      qldRed: "#c4364b",
      qldRedLight: "#7a4048",
      streamGreen: "#6ba83a",
      streamGreenLight: "#3d5a30",
      indicatorOrangeDark: "#974e1f",
      indicatorOrangeLight: "#e87830",
    },
  },
  light: {
    id: "light",
    name: "Light",
    description: "Bright, airy layout.",
    colors: {
      pageBackground: "#e8e8ea",
      pageText: "#323233",
      textPrimary: "#323233",
      panelBackground: "#d4d4d6",
      cardBackground: "#ffffff",
      textMuted: "rgba(50, 50, 51, 0.6)",
      textSecondary: "#666666",
      inputBackground: "#ffffff",
      border: "#c4c4c6",
      buttonPrimary: "#323233",
      menuPurple: "#73658d",
      menuPurpleLight: "#B19CD9",
      outline: "#323233",
      projectCardBackground: "#323233",
      vicBlue: "#4D93D9",
      vicBlueLight: "#A6C9EC",
      qldRed: "#D54358",
      qldRedLight: "#F79198",
      streamGreen: "#92D050",
      streamGreenLight: "#CEEAB0",
      indicatorOrangeDark: "#a65800",
      indicatorOrangeLight: "#ff8800",
    },
  },
  bladeRunner: {
    id: "bladeRunner",
    name: "Blade Runner",
    description: "Rain-soaked dark UI with neon blue, pink, and purple.",
    colors: {
      pageBackground: "#080c14",
      pageText: "#b8f4ff",
      textPrimary: "#d4f1ff",
      panelBackground: "#121a2b",
      cardBackground: "#1a2438",
      textMuted: "rgba(184, 244, 255, 0.55)",
      textSecondary: "#6a8a9e",
      inputBackground: "#0f1624",
      border: "#2a5f78",
      buttonPrimary: "#00e5ff",
      menuPurple: "#241039",
      menuPurpleLight: "#381858",
      outline: "#00e5ff",
      projectCardBackground: "#0f1a28",
      vicBlue: "#00bfff",
      vicBlueLight: "#0a2040",
      qldRed: "#ff2a8a",
      qldRedLight: "#4a1830",
      streamGreen: "#6bff8b",
      streamGreenLight: "#1a3020",
      indicatorOrangeDark: "#a6672c",
      indicatorOrangeLight: "#ff9f43",
    },
  },
  autumn: {
    id: "autumn",
    name: "Autumn",
    description: "Rust, amber, and golden leaves.",
    colors: {
      pageBackground: "#4a2c1a",
      pageText: "#fff8f0",
      textPrimary: "#2a1810",
      panelBackground: "#8b5a2b",
      cardBackground: "#f5e8d8",
      textMuted: "rgba(42, 24, 16, 0.6)",
      textSecondary: "#5c3d28",
      inputBackground: "#f0dcc8",
      border: "#c4a574",
      buttonPrimary: "#b8471f",
      menuPurple: "#463026",
      menuPurpleLight: "#6b4a3a",
      outline: "#3d2414",
      projectCardBackground: "#5c3820",
      vicBlue: "#c45c26",
      vicBlueLight: "#d4894a",
      qldRed: "#8b2942",
      qldRedLight: "#987060",
      streamGreen: "#8b6914",
      streamGreenLight: "#c9a227",
      indicatorOrangeDark: "#8a5930",
      indicatorOrangeLight: "#d4894a",
    },
  },
  winter: {
    id: "winter",
    name: "Winter",
    description: "Frost, ice blue, and snowy greys.",
    colors: {
      pageBackground: "#1a2838",
      pageText: "#e8f4fc",
      textPrimary: "#e8f0f8",
      panelBackground: "#2e4054",
      cardBackground: "#f0f6fc",
      textMuted: "rgba(232, 244, 252, 0.6)",
      textSecondary: "#94a8bc",
      inputBackground: "#243444",
      border: "#4a6080",
      buttonPrimary: "#a8cce8",
      menuPurple: "#30263b",
      menuPurpleLight: "#4a3a5a",
      outline: "#a8cce8",
      projectCardBackground: "#3a5068",
      vicBlue: "#6eb0e8",
      vicBlueLight: "#4a7aa8",
      qldRed: "#c44a5a",
      qldRedLight: "#5a3a48",
      streamGreen: "#5a9a6a",
      streamGreenLight: "#3a5a48",
      indicatorOrangeDark: "#974e1f",
      indicatorOrangeLight: "#e87830",
    },
  },
  summer: {
    id: "summer",
    name: "Summer",
    description: "Sunshine gold and sky blue.",
    colors: {
      pageBackground: "#f0a830",
      pageText: "#1a2838",
      textPrimary: "#1a2838",
      panelBackground: "#4db8e8",
      cardBackground: "#ffffff",
      textMuted: "rgba(26, 40, 56, 0.6)",
      textSecondary: "#3a5870",
      inputBackground: "#ffffff",
      border: "#7ac4e8",
      buttonPrimary: "#e87830",
      menuPurple: "#8c4e97",
      menuPurpleLight: "#d878e8",
      outline: "#1a2838",
      projectCardBackground: "#c87828",
      vicBlue: "#2890c8",
      vicBlueLight: "#4db8e8",
      qldRed: "#d83838",
      qldRedLight: "#f87858",
      streamGreen: "#58b028",
      streamGreenLight: "#90d858",
      indicatorOrangeDark: "#974e1f",
      indicatorOrangeLight: "#e87830",
    },
  },
  spring: {
    id: "spring",
    name: "Spring",
    description: "Fresh meadow greens and blossom pastels.",
    colors: {
      pageBackground: "#6ab878",
      pageText: "#1a3020",
      textPrimary: "#1a3020",
      panelBackground: "#c8e8c0",
      cardBackground: "#ffffff",
      textMuted: "rgba(26, 48, 32, 0.6)",
      textSecondary: "#4a6850",
      inputBackground: "#ffffff",
      border: "#98c8a0",
      buttonPrimary: "#3a8850",
      menuPurple: "#8c7897",
      menuPurpleLight: "#d8b8e8",
      outline: "#2a5038",
      projectCardBackground: "#4a7850",
      vicBlue: "#58a8d8",
      vicBlueLight: "#a8d8f0",
      qldRed: "#c84858",
      qldRedLight: "#f0a8b8",
      streamGreen: "#68b848",
      streamGreenLight: "#b8e8a0",
      indicatorOrangeDark: "#974e1f",
      indicatorOrangeLight: "#e87830",
    },
  },
  christmas: {
    id: "christmas",
    name: "Christmas",
    description: "Evergreen, holly red, and gold trim.",
    colors: {
      pageBackground: "#1a2820",
      pageText: "#f0e8d8",
      textPrimary: "#f0e8d8",
      panelBackground: "#2a4030",
      cardBackground: "#f8f0e0",
      textMuted: "rgba(240, 232, 216, 0.65)",
      textSecondary: "#a8c0a8",
      inputBackground: "#243028",
      border: "#4a6050",
      buttonPrimary: "#c03030",
      menuPurple: "#8a722a",
      menuPurpleLight: "#d4b040",
      outline: "#c9a030",
      projectCardBackground: "#1a4830",
      vicBlue: "#3080c0",
      vicBlueLight: "#5098d0",
      qldRed: "#a02020",
      qldRedLight: "#c03030",
      streamGreen: "#c9a030",
      streamGreenLight: "#208040",
      indicatorOrangeDark: "#974e1f",
      indicatorOrangeLight: "#e87830",
    },
  },
  rainbow: {
    id: "rainbow",
    name: "Rainbow",
    description: "Every menu group a different bright hue.",
    colors: {
      pageBackground: "#1a1a2e",
      pageText: "#ffffff",
      textPrimary: "#f0f0f8",
      panelBackground: "#2a2a40",
      cardBackground: "#f8f8ff",
      textMuted: "rgba(240, 240, 248, 0.65)",
      textSecondary: "#a0a0c0",
      inputBackground: "#222238",
      border: "#4a4a68",
      buttonPrimary: "#ff6b9d",
      menuPurple: "#8151a6",
      menuPurpleLight: "#c77dff",
      outline: "#ffffff",
      projectCardBackground: "#4a3a88",
      vicBlue: "#3aa8e8",
      vicBlueLight: "#6bcbff",
      qldRed: "#ff6b9d",
      qldRedLight: "#ff9f43",
      streamGreen: "#38d858",
      streamGreenLight: "#6bff8b",
      indicatorOrangeDark: "#a6672c",
      indicatorOrangeLight: "#ff9f43",
    },
  },
  oldTime: {
    id: "oldTime",
    name: "Old Time",
    description: "Sepia tones like a faded photograph.",
    colors: {
      pageBackground: "#3e3228",
      pageText: "#e8d8b8",
      textPrimary: "#3a2e22",
      panelBackground: "#5c4a38",
      cardBackground: "#e8dcc0",
      textMuted: "rgba(58, 46, 34, 0.6)",
      textSecondary: "#6a5848",
      inputBackground: "#d8c8a8",
      border: "#a89070",
      buttonPrimary: "#6a5038",
      menuPurple: "#4e4439",
      menuPurpleLight: "#786858",
      outline: "#2a2018",
      projectCardBackground: "#a89068",
      vicBlue: "#887040",
      vicBlueLight: "#a88858",
      qldRed: "#784838",
      qldRedLight: "#987060",
      streamGreen: "#6a7848",
      streamGreenLight: "#8a9868",
      indicatorOrangeDark: "#8a5930",
      indicatorOrangeLight: "#d4894a",
    },
  },
  retro: {
    id: "retro",
    name: "Retro",
    description: "Windows 95 teal desktop.",
    colors: {
      pageBackground: "#008080",
      pageText: "#ffffff",
      textPrimary: "#000000",
      panelBackground: "#008080",
      cardBackground: "#ffffff",
      textMuted: "rgba(0, 0, 0, 0.55)",
      textSecondary: "#404040",
      inputBackground: "#ffffff",
      border: "#808080",
      buttonPrimary: "#c0c0c0",
      menuPurple: "#7d7d7d",
      menuPurpleLight: "#c0c0c0",
      outline: "#000000",
      projectCardBackground: "#E3C07A",
      vicBlue: "#000080",
      vicBlueLight: "#0000aa",
      qldRed: "#800000",
      qldRedLight: "#c0c0c0",
      streamGreen: "#008000",
      streamGreenLight: "#c0c0c0",
      indicatorOrangeDark: "#a65800",
      indicatorOrangeLight: "#ff8800",
    },
  },
};

export const DEFAULT_UI_THEME_ID = "classic";

export const UI_THEME_LIST = [
  UI_THEMES.classic,
  UI_THEMES.dark,
  UI_THEMES.light,
  UI_THEMES.bladeRunner,
  UI_THEMES.autumn,
  UI_THEMES.winter,
  UI_THEMES.summer,
  UI_THEMES.spring,
  UI_THEMES.christmas,
  UI_THEMES.rainbow,
  UI_THEMES.oldTime,
  UI_THEMES.retro,
];

export function getUiTheme(themeId, colorOverrides = {}) {
  const theme = UI_THEMES[themeId] || UI_THEMES.classic;
  const {
    menuBlue: _mb,
    menuBlueActive: _mba,
    menuRed: _mr,
    menuGreen: _mg,
    menuGreenActive: _mga,
    onHoldBanner: _oh,
    cancelledBanner: _cb,
    ...restOverrides
  } = colorOverrides;
  const colors = { ...theme.colors, ...restOverrides };
  const pageText = colors.pageText;
  const textPrimary = colors.textPrimary;
  return {
    ...theme,
    colors: {
      ...colors,
      textMuted: textPrimary,
      textSecondary: textPrimary,
      buttonPrimaryText: pageText,
      menuActiveText: pageText,
      menuBlue: colors.vicBlueLight,
      menuBlueActive: colors.vicBlueLight,
      menuRed: colors.qldRedLight,
      menuGreen: colors.streamGreenLight,
      menuGreenActive: colors.streamGreen,
      onHoldBanner: colors.vicBlue,
      cancelledBanner: colors.qldRed,
      onHoldBannerText: pageText,
      cancelledBannerText: pageText,
      projectCardBackground: colors.projectCardBackground ?? textPrimary,
      projectCardText: pageText,
      menuGroupBorder: colors.outline,
    },
  };
}

export function isValidUiThemeId(themeId) {
  return Boolean(themeId && UI_THEMES[themeId]);
}
