/** Core UI + main sidebar menu colours — status, stream badges, email tints, etc. stay static. */

export const UI_THEME_COLOR_KEYS = [
  { key: "pageBackground", label: "Page" },
  { key: "pageText", label: "Page text" },
  { key: "textPrimary", label: "Menu text - inactive" },
  { key: "panelBackground", label: "Panel" },
  { key: "cardBackground", label: "Card" },
  { key: "textMuted", label: "Muted" },
  { key: "textSecondary", label: "Secondary" },
  { key: "inputBackground", label: "Input" },
  { key: "border", label: "Border" },
  { key: "outline", label: "Outline" },
  { key: "buttonPrimary", label: "Button" },
  { key: "menuBlue", label: "Menu blue" },
  { key: "menuBlueActive", label: "Menu blue on" },
  { key: "menuGreen", label: "Menu green" },
  { key: "menuGreenActive", label: "Menu green on" },
  { key: "menuRed", label: "Menu red" },
  { key: "menuPurple", label: "Menu purple" },
  { key: "onHoldBanner", label: "On hold banner" },
  { key: "cancelledBanner", label: "Cancelled banner" },
  { key: "projectCardBackground", label: "Project folder" },
];

export const UI_THEMES = {
  classic: {
    id: "classic",
    name: "Classic",
    description: "The original SGF look.",
    colors: {
      pageBackground: "#42464d",
      pageText: "#ffffff",
      textPrimary: "#323233",
      panelBackground: "#a1a1a3",
      cardBackground: "#ffffff",
      textMuted: "rgba(50, 50, 51, 0.6)",
      textSecondary: "#404049",
      inputBackground: "#f0f0f0",
      border: "#e0e0e0",
      buttonPrimary: "#323233",
      menuBlue: "#A6C9EC",
      menuBlueActive: "#4D93D9",
      menuGreen: "#CEEAB0",
      menuGreenActive: "#92D050",
      menuRed: "#F79198",
      menuPurple: "#B19CD9",
      outline: "#000000",
      onHoldBanner: "#0066cc",
      cancelledBanner: "#cc0000",
      projectCardBackground: "#323233",
    },
  },
  dark: {
    id: "dark",
    name: "Dark",
    description: "Dark backgrounds with light text.",
    colors: {
      pageBackground: "#000000",
      pageText: "#f0f0f2",
      textPrimary: "#f0f0f2",
      panelBackground: "#1a1e28",
      cardBackground: "#353940",
      textMuted: "rgba(240, 240, 242, 0.65)",
      textSecondary: "#a1a1a3",
      inputBackground: "#1a1e28",
      border: "#4a4f58",
      buttonPrimary: "#e8e8ea",
      menuBlue: "#2a4560",
      menuBlueActive: "#5a9fd4",
      menuGreen: "#2d4a28",
      menuGreenActive: "#6ba83a",
      menuRed: "#5a3038",
      menuPurple: "#443658",
      outline: "#8a919c",
      onHoldBanner: "#3d7bc9",
      cancelledBanner: "#c4364b",
      projectCardBackground: "#353940",
    },
  },
  light: {
    id: "light",
    name: "Light",
    description: "Bright, airy layout.",
    colors: {
      pageBackground: "#e8e8ea",
      pageText: "#323233",
      textPrimary: "#323233",
      panelBackground: "#d4d4d6",
      cardBackground: "#ffffff",
      textMuted: "rgba(50, 50, 51, 0.6)",
      textSecondary: "#666666",
      inputBackground: "#ffffff",
      border: "#c4c4c6",
      buttonPrimary: "#323233",
      menuBlue: "#A6C9EC",
      menuBlueActive: "#4D93D9",
      menuGreen: "#CEEAB0",
      menuGreenActive: "#7ab842",
      menuRed: "#F79198",
      menuPurple: "#B19CD9",
      outline: "#323233",
      onHoldBanner: "#0066cc",
      cancelledBanner: "#cc3333",
      projectCardBackground: "#323233",
    },
  },
  bladeRunner: {
    id: "bladeRunner",
    name: "Blade Runner",
    description: "Rain-soaked dark UI with neon blue, pink, and purple.",
    colors: {
      pageBackground: "#080c14",
      pageText: "#b8f4ff",
      textPrimary: "#d4f1ff",
      panelBackground: "#121a2b",
      cardBackground: "#1a2438",
      textMuted: "rgba(184, 244, 255, 0.55)",
      textSecondary: "#6a8a9e",
      inputBackground: "#0f1624",
      border: "#2a5f78",
      buttonPrimary: "#00e5ff",
      menuBlue: "#0f2848",
      menuBlueActive: "#00bfff",
      menuGreen: "#130710",
      menuGreenActive: "#ff2a8a",
      menuRed: "#16080e",
      menuPurple: "#381858",
      outline: "#00e5ff",
      onHoldBanner: "#00bfff",
      cancelledBanner: "#ff2a8a",
      projectCardBackground: "#0f1a28",
    },
  },
  autumn: {
    id: "autumn",
    name: "Autumn",
    description: "Rust, amber, and golden leaves.",
    colors: {
      pageBackground: "#4a2c1a",
      pageText: "#fff8f0",
      textPrimary: "#2a1810",
      panelBackground: "#8b5a2b",
      cardBackground: "#f5e8d8",
      textMuted: "rgba(42, 24, 16, 0.6)",
      textSecondary: "#5c3d28",
      inputBackground: "#f0dcc8",
      border: "#c4a574",
      buttonPrimary: "#b8471f",
      menuBlue: "#d4894a",
      menuBlueActive: "#c45c26",
      menuGreen: "#c9a227",
      menuGreenActive: "#8b6914",
      menuRed: "#8b2942",
      menuPurple: "#6b4a3a",
      outline: "#3d2414",
      onHoldBanner: "#2e6b9e",
      cancelledBanner: "#8b1a1a",
      projectCardBackground: "#5c3820",
    },
  },
  winter: {
    id: "winter",
    name: "Winter",
    description: "Frost, ice blue, and snowy greys.",
    colors: {
      pageBackground: "#1a2838",
      pageText: "#e8f4fc",
      textPrimary: "#e8f0f8",
      panelBackground: "#2e4054",
      cardBackground: "#f0f6fc",
      textMuted: "rgba(232, 244, 252, 0.6)",
      textSecondary: "#94a8bc",
      inputBackground: "#243444",
      border: "#4a6080",
      buttonPrimary: "#a8cce8",
      menuBlue: "#4a7aa8",
      menuBlueActive: "#6eb0e8",
      menuGreen: "#3a5a48",
      menuGreenActive: "#5a9a6a",
      menuRed: "#5a3a48",
      menuPurple: "#4a3a5a",
      outline: "#a8cce8",
      onHoldBanner: "#3a8cc8",
      cancelledBanner: "#c44a5a",
      projectCardBackground: "#3a5068",
    },
  },
  summer: {
    id: "summer",
    name: "Summer",
    description: "Sunshine gold and sky blue.",
    colors: {
      pageBackground: "#f0a830",
      pageText: "#1a2838",
      textPrimary: "#1a2838",
      panelBackground: "#4db8e8",
      cardBackground: "#ffffff",
      textMuted: "rgba(26, 40, 56, 0.6)",
      textSecondary: "#3a5870",
      inputBackground: "#ffffff",
      border: "#7ac4e8",
      buttonPrimary: "#e87830",
      menuBlue: "#4db8e8",
      menuBlueActive: "#2890c8",
      menuGreen: "#90d858",
      menuGreenActive: "#58b028",
      menuRed: "#f87858",
      menuPurple: "#d878e8",
      outline: "#1a2838",
      onHoldBanner: "#2890c8",
      cancelledBanner: "#d83838",
      projectCardBackground: "#c87828",
    },
  },
  spring: {
    id: "spring",
    name: "Spring",
    description: "Fresh meadow greens and blossom pastels.",
    colors: {
      pageBackground: "#6ab878",
      pageText: "#1a3020",
      textPrimary: "#1a3020",
      panelBackground: "#c8e8c0",
      cardBackground: "#ffffff",
      textMuted: "rgba(26, 48, 32, 0.6)",
      textSecondary: "#4a6850",
      inputBackground: "#ffffff",
      border: "#98c8a0",
      buttonPrimary: "#3a8850",
      menuBlue: "#a8d8f0",
      menuBlueActive: "#58a8d8",
      menuGreen: "#b8e8a0",
      menuGreenActive: "#68b848",
      menuRed: "#f0a8b8",
      menuPurple: "#d8b8e8",
      outline: "#2a5038",
      onHoldBanner: "#4898c8",
      cancelledBanner: "#c84858",
      projectCardBackground: "#4a7850",
    },
  },
  christmas: {
    id: "christmas",
    name: "Christmas",
    description: "Evergreen, holly red, and gold trim.",
    colors: {
      pageBackground: "#1a2820",
      pageText: "#f0e8d8",
      textPrimary: "#f0e8d8",
      panelBackground: "#2a4030",
      cardBackground: "#f8f0e0",
      textMuted: "rgba(240, 232, 216, 0.65)",
      textSecondary: "#a8c0a8",
      inputBackground: "#243028",
      border: "#4a6050",
      buttonPrimary: "#c03030",
      menuBlue: "#c03030",
      menuBlueActive: "#a02020",
      menuGreen: "#208040",
      menuGreenActive: "#c9a030",
      menuRed: "#8b2020",
      menuPurple: "#d4b040",
      outline: "#c9a030",
      onHoldBanner: "#3080c0",
      cancelledBanner: "#601818",
      projectCardBackground: "#1a4830",
    },
  },
  rainbow: {
    id: "rainbow",
    name: "Rainbow",
    description: "Every menu group a different bright hue.",
    colors: {
      pageBackground: "#1a1a2e",
      pageText: "#ffffff",
      textPrimary: "#f0f0f8",
      panelBackground: "#2a2a40",
      cardBackground: "#f8f8ff",
      textMuted: "rgba(240, 240, 248, 0.65)",
      textSecondary: "#a0a0c0",
      inputBackground: "#222238",
      border: "#4a4a68",
      buttonPrimary: "#ff6b9d",
      menuBlue: "#6bcbff",
      menuBlueActive: "#3aa8e8",
      menuGreen: "#6bff8b",
      menuGreenActive: "#38d858",
      menuRed: "#ff9f43",
      menuPurple: "#c77dff",
      outline: "#ffffff",
      onHoldBanner: "#6bcbff",
      cancelledBanner: "#ff6b9d",
      projectCardBackground: "#4a3a88",
    },
  },
  oldTime: {
    id: "oldTime",
    name: "Old Time",
    description: "Sepia tones like a faded photograph.",
    colors: {
      pageBackground: "#3e3228",
      pageText: "#e8d8b8",
      textPrimary: "#3a2e22",
      panelBackground: "#5c4a38",
      cardBackground: "#e8dcc0",
      textMuted: "rgba(58, 46, 34, 0.6)",
      textSecondary: "#6a5848",
      inputBackground: "#d8c8a8",
      border: "#a89070",
      buttonPrimary: "#6a5038",
      menuBlue: "#a88858",
      menuBlueActive: "#887040",
      menuGreen: "#8a9868",
      menuGreenActive: "#6a7848",
      menuRed: "#987060",
      menuPurple: "#786858",
      outline: "#2a2018",
      onHoldBanner: "#5a7a98",
      cancelledBanner: "#784838",
      projectCardBackground: "#a89068",
    },
  },
  retro: {
    id: "retro",
    name: "Retro",
    description: "Windows 95 teal desktop.",
    colors: {
      pageBackground: "#008080",
      pageText: "#ffffff",
      textPrimary: "#000000",
      panelBackground: "#008080",
      cardBackground: "#ffffff",
      textMuted: "rgba(0, 0, 0, 0.55)",
      textSecondary: "#404040",
      inputBackground: "#ffffff",
      border: "#808080",
      buttonPrimary: "#c0c0c0",
      menuBlue: "#000080",
      menuBlueActive: "#000080",
      menuGreen: "#c0c0c0",
      menuGreenActive: "#000080",
      menuRed: "#c0c0c0",
      menuPurple: "#c0c0c0",
      outline: "#000000",
      onHoldBanner: "#0000ff",
      cancelledBanner: "#800000",
      projectCardBackground: "#E3C07A",
    },
  },
};

export const DEFAULT_UI_THEME_ID = "classic";

export const UI_THEME_LIST = [
  UI_THEMES.classic,
  UI_THEMES.dark,
  UI_THEMES.light,
  UI_THEMES.bladeRunner,
  UI_THEMES.autumn,
  UI_THEMES.winter,
  UI_THEMES.summer,
  UI_THEMES.spring,
  UI_THEMES.christmas,
  UI_THEMES.rainbow,
  UI_THEMES.oldTime,
  UI_THEMES.retro,
];

export function getUiTheme(themeId, colorOverrides = {}) {
  const theme = UI_THEMES[themeId] || UI_THEMES.classic;
  const colors = { ...theme.colors, ...colorOverrides };
  const pageText = colors.pageText;
  return {
    ...theme,
    colors: {
      ...colors,
      buttonPrimaryText: pageText,
      menuActiveText: pageText,
      onHoldBannerText: pageText,
      cancelledBannerText: pageText,
      projectCardBackground: colors.projectCardBackground ?? colors.textPrimary,
      projectCardText: pageText,
      menuGroupBorder: colors.outline,
    },
  };
}

export function isValidUiThemeId(themeId) {
  return Boolean(themeId && UI_THEMES[themeId]);
}
